// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2X4NEBV8hck_01ewWXYcejA3Q-Za5QAU',
    appId: '1:67186491639:web:91569d0113cd9dc9f613f2',
    messagingSenderId: '67186491639',
    projectId: 'waterapp-463817',
    authDomain: 'waterapp-463817.firebaseapp.com',
    storageBucket: 'waterapp-463817.firebasestorage.app',
    measurementId: 'G-CJM35GYG6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPgwpl7S2qaF0y0iXu9TUn4AhRWSv5vVk',
    appId: '1:67186491639:android:d432ba0ee9bbaaeaf613f2',
    messagingSenderId: '67186491639',
    projectId: 'waterapp-463817',
    storageBucket: 'waterapp-463817.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzq6gY4sU1yWGO83jEolv--IuhZ6vu_IQ',
    appId: '1:67186491639:ios:aa0a7a48f1941f9bf613f2',
    messagingSenderId: '67186491639',
    projectId: 'waterapp-463817',
    storageBucket: 'waterapp-463817.firebasestorage.app',
    iosBundleId: 'com.example.waterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzq6gY4sU1yWGO83jEolv--IuhZ6vu_IQ',
    appId: '1:67186491639:ios:aa0a7a48f1941f9bf613f2',
    messagingSenderId: '67186491639',
    projectId: 'waterapp-463817',
    storageBucket: 'waterapp-463817.firebasestorage.app',
    iosBundleId: 'com.example.waterapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2X4NEBV8hck_01ewWXYcejA3Q-Za5QAU',
    appId: '1:67186491639:web:1396bbbb015f52ccf613f2',
    messagingSenderId: '67186491639',
    projectId: 'waterapp-463817',
    authDomain: 'waterapp-463817.firebaseapp.com',
    storageBucket: 'waterapp-463817.firebasestorage.app',
    measurementId: 'G-MH8WR4TRMN',
  );

}